"use client";

import { useMemo, useState } from "react";
import { sales, type Sale } from "./sales-data";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowUpRight, CarFront, CheckCircle2, CircleDollarSign, Clock3, Gauge, RotateCcw, Trophy } from "lucide-react";

const ALL="Todos", MIN_DATE="2024-02-28", MAX_DATE="2027-10-01";
const colors=["#d5001c","#857c77","#4c6a78","#c5a880","#111111","#6f8a74"];
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"USD",maximumFractionDigits:0});
const integer=new Intl.NumberFormat("pt-BR");
const unique=<K extends keyof Sale>(key:K)=>[...new Set(sales.map(i=>i[key]))].sort((a,b)=>String(a).localeCompare(String(b),"pt-BR",{numeric:true}));
const quarter=(date:string)=>{const d=new Date(`${date}T00:00:00`);return `${d.getFullYear()} T${Math.floor(d.getMonth()/3)+1}`};
function countBy(items:Sale[],key:keyof Sale){const m=new Map<string,number>();items.forEach(i=>m.set(String(i[key]),(m.get(String(i[key]))??0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function family(model:string){return ["911","Cayenne","Macan","Taycan","Panamera","718"].find(f=>model.startsWith(f))??"Outros"}
function powertrain(model:string){return /Taycan|Electric|E-Hybrid/.test(model)?"Eletrificados":"Combustão"}
function SelectFilter({label,value,options,onChange}:{label:string;value:string;options:(string|number)[];onChange:(v:string)=>void}){return <label className="filter-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value={ALL}>{ALL}</option>{options.map(o=><option key={String(o)} value={String(o)}>{o}</option>)}</select></label>}
function DateFilter({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="filter-field"><span>{label}</span><input type="date" min={MIN_DATE} max={MAX_DATE} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <article className="metric-card"><div className="metric-icon">{icon}</div><div><p>{label}</p><strong>{value}</strong><span>{detail}</span></div></article>}
const tooltipStyle={background:"#fff",border:"1px solid #ddd9d6",borderRadius:12,boxShadow:"0 16px 40px rgba(0,0,0,.12)",fontSize:13};

export default function Home(){
 const [model,setModel]=useState(ALL),[year,setYear]=useState(ALL),[city,setCity]=useState(ALL),[payment,setPayment]=useState(ALL),[status,setStatus]=useState(ALL),[dateFrom,setDateFrom]=useState(MIN_DATE),[dateTo,setDateTo]=useState(MAX_DATE);
 const baseFiltered=useMemo(()=>sales.filter(s=>(model===ALL||s.model===model)&&(year===ALL||String(s.year)===year)&&(city===ALL||s.city===city)&&(payment===ALL||s.payment===payment)&&(status===ALL||s.status===status)),[model,year,city,payment,status]);
 const filtered=useMemo(()=>baseFiltered.filter(s=>s.date>=dateFrom&&s.date<=dateTo),[baseFiltered,dateFrom,dateTo]);
 const analytics=useMemo(()=>{
  const revenue=filtered.reduce((a,i)=>a+i.price,0),avg=filtered.length?revenue/filtered.length:0,models=countBy(filtered,"model"),years=countBy(filtered,"year"),delivered=filtered.filter(i=>i.status==="Delivered").length,cancelled=filtered.filter(i=>i.status==="Cancelled"),pending=filtered.filter(i=>i.status!=="Delivered"&&i.status!=="Cancelled");
  const cityMap=new Map<string,{city:string;state:string;sales:number;revenue:number;models:Map<string,number>;delivered:number}>();
  filtered.forEach(i=>{const e=cityMap.get(i.city)??{city:i.city,state:i.state,sales:0,revenue:0,models:new Map(),delivered:0};e.sales++;e.revenue+=i.price;if(i.status==="Delivered")e.delivered++;e.models.set(i.model,(e.models.get(i.model)??0)+1);cityMap.set(i.city,e)});
  const cities=[...cityMap.values()].map(i=>({city:i.city,state:i.state,sales:i.sales,revenue:i.revenue,deliveryRate:i.sales?i.delivered/i.sales:0,topModel:[...i.models.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]??"—"})).sort((a,b)=>b.revenue-a.revenue);
  const topCities=cities.slice(0,5).map(i=>i.city),quarters=[...new Set(filtered.map(i=>quarter(i.date)))].sort(),running=Object.fromEntries(topCities.map(n=>[n,0])) as Record<string,number>;
  const evolution=quarters.map(period=>{const row:Record<string,string|number>={period};topCities.forEach(n=>{running[n]+=filtered.filter(i=>i.city===n&&quarter(i.date)===period).reduce((a,i)=>a+i.price,0);row[n]=running[n]});return row});
  const mm=new Map<string,number>();filtered.forEach(i=>{const m=i.date.slice(0,7);mm.set(m,(mm.get(m)??0)+i.price)});const monthly=[...mm.entries()].sort().map(([month,value])=>({month:month.replace("-","/"),value}));
  const families=[...new Set(filtered.map(i=>family(i.model)))].map(name=>({name,value:filtered.filter(i=>family(i.model)===name).length})).sort((a,b)=>b.value-a.value);
  const payments=[...new Set(filtered.map(i=>i.payment))].map(name=>({name,value:filtered.filter(i=>i.payment===name).reduce((a,i)=>a+i.price,0)})).sort((a,b)=>b.value-a.value).slice(0,6);
  const statuses=countBy(filtered,"status").map(([name,value])=>({name,value}));
  const power=["Eletrificados","Combustão"].map(name=>({name,value:filtered.filter(i=>powertrain(i.model)===name).length}));
  const start=new Date(`${dateFrom}T00:00:00`),end=new Date(`${dateTo}T00:00:00`),days=Math.max(1,Math.round((end.getTime()-start.getTime())/86400000)+1),prevEnd=new Date(start.getTime()-86400000),prevStart=new Date(prevEnd.getTime()-(days-1)*86400000),iso=(d:Date)=>d.toISOString().slice(0,10);
  const previous=baseFiltered.filter(i=>i.date>=iso(prevStart)&&i.date<=iso(prevEnd)),previousRevenue=previous.reduce((a,i)=>a+i.price,0),delta=previousRevenue?((revenue-previousRevenue)/previousRevenue)*100:null;
  const bestCity=cities[0],highCancelCity=[...cities].filter(c=>filtered.some(i=>i.city===c.city&&i.status==="Cancelled")).sort((a,b)=>filtered.filter(i=>i.city===b.city&&i.status==="Cancelled").length-filtered.filter(i=>i.city===a.city&&i.status==="Cancelled").length)[0];
  const insights=[bestCity?`${bestCity.city} lidera a receita com ${money.format(bestCity.revenue)} e ${bestCity.sales} venda${bestCity.sales>1?"s":""}.`:"",models[0]?`${models[0][0]} é o modelo líder em volume, com ${models[0][1]} unidade${models[0][1]>1?"s":""}.`:"",payments[0]?`${payments[0].name} concentra o maior valor transacionado: ${money.format(payments[0].value)}.`:"",power[0].value?`${Math.round(power[0].value/filtered.length*100)}% das vendas selecionadas são de modelos eletrificados.`:""].filter(Boolean);
  const alerts=[cancelled.length?`${cancelled.length} venda${cancelled.length>1?"s":""} cancelada${cancelled.length>1?"s":""}, somando ${money.format(cancelled.reduce((a,i)=>a+i.price,0))}.`:"Nenhum cancelamento no recorte selecionado.",pending.length?`${money.format(pending.reduce((a,i)=>a+i.price,0))} permanecem em operações ainda não entregues.`:"Todas as operações válidas já foram entregues.",highCancelCity?`${highCancelCity.city} merece atenção por registrar cancelamento no período.`:"Não há praça com alerta de cancelamento." ];
  return{revenue,avg,models,years,delivered,cancelled,pending,cities,topCities,evolution,monthly,families,payments,statuses,power,delta,insights,alerts};
 },[filtered,baseFiltered,dateFrom,dateTo]);
 const reset=()=>{setModel(ALL);setYear(ALL);setCity(ALL);setPayment(ALL);setStatus(ALL);setDateFrom(MIN_DATE);setDateTo(MAX_DATE)};
 return <main>
  <header className="topbar"><div className="brand">PORSCHE</div><div className="title-lockup"><span>Sales Intelligence</span><small>Performance &amp; market pulse</small></div><div className="period-pill">Fev 2024 — Out 2027</div></header>
  <section className="hero-band"><div><p className="eyebrow">DIO · Dashboard com agentes de IA</p><h1>Precisão que transforma<br/>dados em direção.</h1></div><div className="hero-stat"><span>Base analisada</span><strong>100</strong><small>negociações Porsche</small></div></section>
  <section className="filter-panel expanded" aria-label="Filtros do dashboard"><SelectFilter label="Modelo Porsche" value={model} options={unique("model")} onChange={setModel}/><SelectFilter label="Ano do modelo" value={year} options={unique("year")} onChange={setYear}/><SelectFilter label="Cidade" value={city} options={unique("city")} onChange={setCity}/><SelectFilter label="Pagamento" value={payment} options={unique("payment")} onChange={setPayment}/><SelectFilter label="Status" value={status} options={unique("status")} onChange={setStatus}/><DateFilter label="Venda: de" value={dateFrom} onChange={setDateFrom}/><DateFilter label="Venda: até" value={dateTo} onChange={setDateTo}/><button className="reset-button" onClick={reset}><RotateCcw size={17}/> Limpar</button></section>
  <section className="metrics-grid"><Metric icon={<CircleDollarSign/>} label="Receita total" value={money.format(analytics.revenue)} detail={analytics.delta===null?`${integer.format(filtered.length)} vendas selecionadas`:`${analytics.delta>=0?"+":""}${analytics.delta.toFixed(1)}% vs. período anterior`}/><Metric icon={<CarFront/>} label="Volume de vendas" value={integer.format(filtered.length)} detail={`${filtered.length?Math.round(analytics.delivered/filtered.length*100):0}% já entregues`}/><Metric icon={<Gauge/>} label="Ticket médio" value={money.format(analytics.avg)} detail="valor médio por veículo"/><Metric icon={<Trophy/>} label="Ano líder" value={analytics.years[0]?.[0]??"—"} detail={`${analytics.years[0]?.[1]??0} veículos vendidos`}/></section>
  {filtered.length===0?<section className="empty-state"><h2>Nenhuma venda nesta combinação.</h2><p>Ajuste os filtros ou o período para ampliar a análise.</p><button onClick={reset}>Restaurar visão geral</button></section>:<>
   <section className="ops-strip"><div><CheckCircle2/><span>Taxa de entrega</span><strong>{Math.round(analytics.delivered/filtered.length*100)}%</strong></div><div><AlertTriangle/><span>Taxa de cancelamento</span><strong>{Math.round(analytics.cancelled.length/filtered.length*100)}%</strong></div><div><Clock3/><span>Operações em aberto</span><strong>{analytics.pending.length}</strong></div><div><CircleDollarSign/><span>Receita pendente</span><strong>{money.format(analytics.pending.reduce((a,i)=>a+i.price,0))}</strong></div></section>
   <section className="insight-row"><div className="insight-copy"><span className="section-index">01</span><p>Modelo mais vendido</p><h2>{analytics.models[0]?.[0]}</h2><div className="rank-strip">{analytics.models.slice(0,4).map(([name,value],index)=><div key={name}><span>0{index+1}</span><strong>{name}</strong><small>{value} venda{value>1?"s":""}</small></div>)}</div></div><div className="spark-card"><div className="chart-heading"><div><span>Evolução da receita</span><h3>Ritmo mensal</h3></div><ArrowUpRight/></div><ResponsiveContainer width="100%" height={220}><AreaChart data={analytics.monthly} margin={{top:15,right:5,left:-20,bottom:0}}><defs><linearGradient id="redFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d5001c" stopOpacity={.34}/><stop offset="100%" stopColor="#d5001c" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e5e1de" vertical={false}/><XAxis dataKey="month" tick={{fill:"#756f6b",fontSize:11}} tickLine={false} axisLine={false} minTickGap={34}/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`} tick={{fill:"#756f6b",fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v=>money.format(Number(v))}/><Area type="monotone" dataKey="value" name="Receita" stroke="#d5001c" strokeWidth={2.5} fill="url(#redFade)"/></AreaChart></ResponsiveContainer></div></section>
   <section className="chart-grid"><article className="chart-card wide"><div className="chart-heading"><div><span>02 · Vendas por cidade</span><h3>Evolução acumulada — Top 5 em receita</h3></div><small>Valores em USD</small></div><ResponsiveContainer width="100%" height={330}><LineChart data={analytics.evolution} margin={{top:15,right:16,left:8,bottom:0}}><CartesianGrid stroke="#e5e1de" vertical={false}/><XAxis dataKey="period" tick={{fill:"#756f6b",fontSize:12}} tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`} tick={{fill:"#756f6b",fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v=>money.format(Number(v))}/><Legend/>{analytics.topCities.map((n,i)=><Line key={n} type="monotone" dataKey={n} stroke={colors[i]} strokeWidth={2.5} dot={{r:2.5}} activeDot={{r:5}}/>)}</LineChart></ResponsiveContainer></article><article className="chart-card"><div className="chart-heading"><div><span>03 · Mercado local</span><h3>Cidades por receita</h3></div></div><ResponsiveContainer width="100%" height={330}><BarChart data={analytics.cities.slice(0,8)} layout="vertical" margin={{top:10,right:8,left:6,bottom:0}}><CartesianGrid stroke="#e5e1de" horizontal={false}/><XAxis type="number" tickFormatter={v=>`$${Math.round(v/1000)}k`} tick={{fill:"#756f6b",fontSize:10}} tickLine={false} axisLine={false}/><YAxis type="category" dataKey="city" width={90} tick={{fill:"#332f2d",fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v=>money.format(Number(v))}/><Bar dataKey="revenue" name="Receita" fill="#d5001c" radius={[0,5,5,0]} barSize={14}/></BarChart></ResponsiveContainer></article></section>
   <section className="city-section"><div className="section-title"><div><span>04 · Preferência por praça</span><h2>Os Porsche mais populares em cada cidade.</h2></div><p>A classificação combina volume de vendas e receita para revelar a força de cada mercado local.</p></div><div className="city-table-wrap"><table><thead><tr><th>#</th><th>Cidade</th><th>Modelo principal</th><th>Vendas</th><th>Receita</th><th>Taxa de entrega</th></tr></thead><tbody>{analytics.cities.slice(0,12).map((i,index)=><tr key={i.city}><td>{String(index+1).padStart(2,"0")}</td><td><strong>{i.city}</strong><span>{i.state}</span></td><td>{i.topModel}</td><td>{i.sales}</td><td>{money.format(i.revenue)}</td><td>{Math.round(i.deliveryRate*100)}%</td></tr>)}</tbody></table></div></section>
   <section className="intelligence-section"><div className="section-title"><div><span>05 · Inteligência comercial</span><h2>O que os dados revelam.</h2></div><p>Participação de portfólio, comportamento de pagamento e saúde operacional no mesmo recorte dos filtros.</p></div><div className="intelligence-grid"><article className="mini-chart"><div className="chart-heading"><div><span>Portfólio</span><h3>Famílias Porsche</h3></div></div><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={analytics.families} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{analytics.families.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/><Legend/></PieChart></ResponsiveContainer></article><article className="mini-chart"><div className="chart-heading"><div><span>Receita</span><h3>Métodos de pagamento</h3></div></div><ResponsiveContainer width="100%" height={250}><BarChart data={analytics.payments} margin={{top:4,right:6,left:-2,bottom:30}}><CartesianGrid stroke="#e5e1de" vertical={false}/><XAxis dataKey="name" angle={-25} textAnchor="end" tick={{fill:"#756f6b",fontSize:10}} tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`} tick={{fill:"#756f6b",fontSize:10}} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v=>money.format(Number(v))}/><Bar dataKey="value" name="Receita" fill="#111" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></article><article className="mini-chart"><div className="chart-heading"><div><span>Transição energética</span><h3>Eletrificados x combustão</h3></div></div><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={analytics.power} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88}>{analytics.power.map((_,i)=><Cell key={i} fill={i===0?"#d5001c":"#262626"}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/><Legend/></PieChart></ResponsiveContainer></article></div><div className="intelligence-notes"><article className="ai-insights"><span>INSIGHTS AUTOMÁTICOS</span><h3>Leitura executiva</h3>{analytics.insights.map((text,i)=><p key={text}><b>0{i+1}</b>{text}</p>)}</article><article className="risk-panel"><span>PONTOS DE ATENÇÃO</span><h3>Saúde das operações</h3>{analytics.alerts.map((text,i)=><p key={text} className={i===0&&analytics.cancelled.length?"warning":""}>{i===0&&analytics.cancelled.length?<AlertTriangle/>:<CheckCircle2/>}{text}</p>)}</article></div></section>
  </>}
  <footer><span>PORSCHE SALES INTELLIGENCE</span><p>Projeto acadêmico independente · Dados fornecidos para o desafio DIO</p><small>100 registros · 2024–2027 · valores em USD</small></footer>
 </main>
}
